# -*- coding: utf-8 -*-
"""BT_Emo_Minority.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyOyMDwxsZuWUn7VG9xsSHr5QxClBTHQ
"""

from transformers import BertForSequenceClassification
from torch.optim import  AdamW
import torch.nn.functional as F
import torch.nn as nn
from sklearn.metrics import accuracy_score
import numpy as np

from google.colab import files
import pandas as pd

# Step 1: Upload dataset
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Step 2: Load the dataset (assuming 2 columns: text, label)
df = pd.read_csv(filename)
df = df.iloc[:, :2]
df.columns = ['text', 'label']

# Step 3: Ensure correct types
df = df.dropna()
df['label'] = df['label'].astype(int)
df['text'] = df['text'].astype(str)

# Step 4: Show stats
print("✅ Loaded:", df.shape)
print("✅ Label distribution:\n", df['label'].value_counts())

from sklearn.model_selection import train_test_split
from transformers import BertTokenizer
from torch.utils.data import Dataset, DataLoader
import torch

forget_label = 3

forget_df = df[df['label'] == forget_label]
retain_df = df[df['label'] != forget_label]

forget_train, forget_val = train_test_split(forget_df, test_size=0.2, random_state=42)
retain_train, retain_val = train_test_split(retain_df, test_size=0.2, random_state=42)
val_df = pd.concat([forget_val, retain_val]).sample(frac=1, random_state=42)

# Tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

class EmotionDataset(Dataset):
    def __init__(self, texts, labels):
        self.enc = tokenizer(texts, padding=True, truncation=True, return_tensors='pt', max_length=128)
        self.labels = torch.tensor(labels)
    def __getitem__(self, i):
        return {k: v[i] for k, v in self.enc.items()} | {'labels': self.labels[i]}
    def __len__(self): return len(self.labels)

batch_size = 16
retain_loader = DataLoader(EmotionDataset(retain_train['text'].tolist(), retain_train['label'].tolist()), batch_size, shuffle=True)
forget_loader = DataLoader(EmotionDataset(forget_train['text'].tolist(), forget_train['label'].tolist()), batch_size, shuffle=True)
val_loader = DataLoader(EmotionDataset(val_df['text'].tolist(), val_df['label'].tolist()), batch_size)

# === LOSS FUNCTIONS ===
class FocalLoss(nn.Module):
    def __init__(self, gamma=2.0, alpha=0.25, reduction='mean'):
        super().__init__()
        self.gamma = gamma
        self.alpha = alpha
        self.reduction = reduction
        self.ce = nn.CrossEntropyLoss(reduction='none')
    def forward(self, inputs, targets):
        ce_loss = self.ce(inputs, targets)
        pt = torch.exp(-ce_loss)
        return (self.alpha * (1 - pt) ** self.gamma * ce_loss).mean()

cosine = nn.CosineEmbeddingLoss()
huber = nn.SmoothL1Loss()
focal = FocalLoss()

# === INITIALIZE MODELS ===
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
num_labels = df['label'].nunique()

def init_model():
    return BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=num_labels).to(device)

# === TRAIN SMART TEACHER ===
def train_teacher(model, loader):
    model.train()
    opt = AdamW(model.parameters(), lr=2e-5)
    for epoch in range(2):
        for batch in loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            loss = model(**batch).loss
            opt.zero_grad(); loss.backward(); opt.step()

# === EVALUATE ===
def evaluate_student(model, forget_label):
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for batch in val_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            preds = model(**batch).logits.argmax(dim=1).cpu().numpy()
            labels = batch['labels'].cpu().numpy()
            all_preds.extend(preds); all_labels.extend(labels)
    all_preds = np.array(all_preds); all_labels = np.array(all_labels)
    val_acc = accuracy_score(all_labels, all_preds)
    forget_acc = accuracy_score(all_labels[all_labels==forget_label], all_preds[all_labels==forget_label])
    retain_acc = accuracy_score(all_labels[all_labels!=forget_label], all_preds[all_labels!=forget_label])
    print(f"✅ Validation Accuracy: {val_acc*100:.2f}%")
    print(f"📉 Forget Class [{forget_label}] Accuracy: {forget_acc*100:.2f}%")
    print(f"📈 Retain Class Accuracy: {retain_acc*100:.2f}%")
    return val_acc, forget_acc, retain_acc

# === BAD TEACHER TRAINING FUNCTION ===
def train_student_bad_teacher(student, smart_teacher, bad_teacher, loss_type='kl_ce', temp=2.0, epochs=3):
    student.train()
    opt = AdamW(student.parameters(), lr=2e-5)

    for epoch in range(epochs):
        total_loss = 0
        for ret_batch, forg_batch in zip(retain_loader, forget_loader):
            ret_batch = {k: v.to(device) for k, v in ret_batch.items()}
            forg_batch = {k: v.to(device) for k, v in forg_batch.items()}

            with torch.no_grad():
                t_smart_ret = smart_teacher(**ret_batch).logits.detach()
                t_bad_forg = bad_teacher(**forg_batch).logits.detach()

            s_ret = student(**ret_batch).logits
            s_forg = student(**forg_batch).logits

            if loss_type == 'kl_ce':
                soft = F.log_softmax(s_ret/temp, dim=1)
                target = F.softmax(t_smart_ret/temp, dim=1)
                loss = F.kl_div(soft, target, reduction='batchmean') * temp**2 + \
                       F.cross_entropy(s_ret, ret_batch['labels'])

            elif loss_type == 'cosine_embedding':
                retain_targets = torch.ones(s_ret.size(0)).to(device)
                forget_targets = -1 * torch.ones(s_forg.size(0)).to(device)
                retain_loss = cosine(s_ret, t_smart_ret, retain_targets)
                forget_loss = cosine(s_forg, t_bad_forg, forget_targets)
                loss = retain_loss + forget_loss

            elif loss_type == 'huber':
                loss = huber(s_ret, t_smart_ret)

            elif loss_type == 'mse':
                loss = F.mse_loss(s_ret, t_smart_ret)

            elif loss_type == 'focal':
                loss = focal(s_ret, ret_batch['labels'])

            opt.zero_grad(); loss.backward(); opt.step()
            total_loss += loss.item()

        print(f"Epoch {epoch+1}/{epochs} | {loss_type} Loss: {total_loss / len(retain_loader):.4f}")

# === MASTER LOOP ===
forget_label = 5
train_df = pd.concat([retain_loader, forget_loader])
train_loader = DataLoader(EmotionDataset(train_df['text'].tolist(), train_df['label'].tolist()), batch_size=16, shuffle=True)

smart_teacher = init_model()
train_teacher(smart_teacher, train_loader)
bad_teacher = init_model()  # Not trained

losses = ['kl_ce', 'cosine_embedding', 'huber', 'mse', 'focal']
results = []

for loss_type in losses:
    print(f"\n🔁 Training student with {loss_type.upper()} loss")
    student = init_model()
    student.load_state_dict(smart_teacher.state_dict())
    train_student_bad_teacher(student, smart_teacher, bad_teacher, loss_type)
    val_acc, f_acc, r_acc = evaluate_student(student, forget_label)
    results.append({'Loss': loss_type, 'Val Acc': val_acc, 'Forget Acc': f_acc, 'Retain Acc': r_acc})

# === SUMMARY ===
import pandas as pd
print("Bad Teacher on Emoiton dataset")
print(pd.DataFrame(results).sort_values("Forget Acc"))











